model:
  name: HGNet
  pretrained_model:
  input_shape: &input_shape [256, 512]
  structure:
  - block_name: Stem
    hidden_channel: 24
    out_channel: 32
    stride: [2, 2]
    bias: True
  - block_name: [HGBlock, ConvBNAct]
    num_block: [1, 1]
    hidden_channel: [32, 48]
    out_channel: [64, 256]
    stride: [1, 2]
    num_layers: 4
    kernel_size: 3
    padding: 1
    act: GELU
  - block_name: [HGBlock, CTConvBNAct]
    num_block: [2, 1]
    hidden_channel: [96, 192]
    out_channel: [512, 1024]
    stride: [2, 2]
    num_layers: 6
    kernel_size: 5
    padding: 2
    act: GELU
  - block_name: Rearrange
    pattern: b c h w -> b (h w) c
  - block_name: AttnHead
    hidden_channel: 768
    out_channel: 10
    head: 64
    group: 6
    # **kwargs

datareader:
  reader:
    name: Searcher
    root_path: None
    dataset_path: /home/a430/LXQ/water_pipeline
  call:
    name: read_dataset
    label: all
    equal: False
    T: 10
  # **other_params

program:
  name: Trainer
  use_amp: true
  stop_patience: 200
  monite_value: mAP
  compare_type: max
  log_dir: water_pipline_logs/HGNet
  log_items: scalar
  verbose: true
  callbacks:
    name: Callbacks2Head
    keys: [ precise, recall, mAP ]
  num_epochs: 200
  step_per_epoch: &step_per_epoch 250

train:
  dataset:
    name: BasicDataset
    input_shape: *input_shape
    random: strong   # if SSLDataset ['strong', ...]
  loader:
    batch_size: 256
    step_per_epoch: *step_per_epoch
    num_workers: 32
    shuffle: true
    pin_memory: false
    persistent_workers: true
    # prefetch_factor: 2

valid:
  dataset:
    name: BasicDataset
    input_shape: *input_shape
    random: valid
  loader:
    batch_size: 128
    num_workers: 4
    shuffle: false
    pin_memory: false
    persistent_workers: true
    # prefetch_factor: 2

optimizer:
  name: AdamW
  lr: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 1e-2
  lr_scheduler:
    name: CosineAnnealingLR
    T_max: 50000

loss:
  name: cross_entropy_2head
  weight_0: [0.25, 0.25, 0.85, 0.85, 2.5, 1.3]
  weight_1: [0.13, 1.29, 1.29, 1.29]
